apiVersion: v1
kind: Service
metadata:
  name: devops-node-api-service-user1
spec:
  type: NodePort
  selector:
    app: devops-node-api-user1
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 40007
